### PR TITLE
Migrate to manifest v3

### LINKED ISSUE #84: Migrate to manifest v3
Here is more information on it: [chrome](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/) | [firefox](https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/)

One of the biggest changes I'm seeing is service workers instead of background.js now, and the opportunity to move towards promise based apis instead of the callback method chrome had us using.

> **Chrome**
> Manifest V3 is available beginning with **Chrome 88**, and the Chrome Web Store begins accepting MV3 extensions in **January 2021**.

> **Firefox**
> As of this writing, we are hoping to complete enough work on this project to support developer testing in Q4 2021 and start accepting v3 submissions in **early 2022**.

Firefox could be a blocker here until next year.

### PR DESCRIPTION
**Pull request by erzhan-temir-mamyrov**
Closes #84 

Add support for Manifest v3

##### New

- Add new package for Manifest v2 (FIrefox issue)

##### Changed

- Update functions in `utilities` package to support v3
- Update main package to support v3

#### Testing / Reviewing

- Navigate to `web-extenstion` (Manifest v3) or `web-extension-v2` (Manifest v2) package and run `yarn watch` or `yarn build`.
- Setup Chrome (v3) / Firefox (v2) browser with custom extension. 
- Open any website built using Carbon.
- Verify Devtools functionality.

### CODE REVIEW

**Comment by erzhan-temir-mamyrov** [comment]
Reviewers: @motou

**Comment by motou** [comment]
Nice job! 👍  Already checked with https://developer.chrome.com/docs/extensions/mv3/mv3-migration/

**Comment by motou** [comment]
Looks so far so good from the code changes. Please adjust the Github action file to make sure that the correct version is published to different stores:

https://github.com/carbon-design-system/devtools/blob/base/.github/workflows/publish.yml

**Comment by erzhan-temir-mamyrov** [comment]
@motou Thank you very much for the feedback! I corrected pipeline according to new changes.

**Comment by motou** [comment]
Awesome👍thanks for your contribution! @erzhan-temir-mamyrov

**Comment by erzhan-temir-mamyrov** [comment]
@motou Thank you for the support! I am wondering which issue I could tackle next, or I could pick up any from the list? I guess bugs have higher priority than enhancements.

**Pull request merged**
