### PR TITLE
chore(demo-site): remove demo site package

### PR DESCRIPTION
**Pull request by andy-blum**
> [!NOTE]
> This PR is a part of my exploration into the devtools to understand how they work, how to update them for use with the next version of Carbon and carbon-based libraries, and how to make them more maintainable going forward. Full documentation is available [here](https://ibm.box.com/s/nlyfnt0uo1aof9ocnxxfcy16oe0kcghz) (w3ID required)

This PR removes the demo-site package, for several reasons:

* The package appears to no longer function correctly, as running the yarn commands fails to start up the next.js app in any meaningful way.
* The package has not had a commit since #261, nearly 2 years ago.
* The public version of this package, https://carbon-design-system.github.io/devtools/, is built from this repository's `gh-pages` branch which appears to be just a static build.
* Adding the web-ext package would allow us to test the extension against live sites easily

##### Removed

- Removes the demo-site package

### CODE REVIEW

**Comment by motou** [comment]
Thanks Andy for raising the PR. Please take a look at the failed PR checks. It seems that the web extension cannot be built now.

**Comment by andy-blum** [comment]
Been digging into that - it's definitely still building locally on the same versions of node & npm.

**Comment by m4olivei** [comment]
I can reporduce the issue locally. Seems to be an order of operations thing. The build fails on `Error: Can't resolve '@carbon/devtools-component-list/dist/index.json'`. That file is only created once you've run `yarn build` on the `packages/component-list` package. If I do that first, and then `yarn build` the entire project, all is well.

This same issue is present on the `base` branch. It's maybe just a matter of declaring the dependency on `@carbon/devtools-component-list` from `carbon-devtools`?

**Comment by m4olivei** [comment]
This is working for me locally. Lets see how it does in CI: https://github.com/carbon-design-system/devtools/pull/318

**Comment by m4olivei** [comment]
CI is clean over in https://github.com/carbon-design-system/devtools/pull/318 🙌

**Review by motou — APPROVED** [review]
Please also check if lerna config needs to be adjusted

**Comment by andy-blum** [comment]
@motou you mean the [lerna.json](https://github.com/carbon-design-system/devtools/blob/base/lerna.json) file?

```json
{
  "version": "2.3.3",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```

What would need changed?

**Comment by motou** [comment]
Yes, we may need to remove the workspaces that are already removed

**Comment by motou** [comment]
On the other side, if the demo site is removed, please provide a website that uses Carbon v10 in the readme file so that the dev tools can be triggered.

**Review by motou — APPROVED** [review]

**Pull request merged**
